-- Seed exercícios: Peitoral e Dorsal/Costas (variações completas)
with novos(name, muscle_group, secondary_muscle, secondary_muscle_2) as (
  values
    ('Supino reto barra','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino reto halteres','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino reto pegada neutra com halteres','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino reto articulado','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino reto articulado unilateral','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino articulado convergente','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino articulado convergente unilateral','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino máquina','Peitoral','Tríceps','Deltoide anterior'),
    ('Chest press','Peitoral','Tríceps','Deltoide anterior'),
    ('Chest press articulado','Peitoral','Tríceps','Deltoide anterior'),
    ('Chest press articulado unilateral','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino convergente','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino unilateral na máquina','Peitoral','Tríceps','Deltoide anterior'),
    ('Floor press barra','Peitoral','Tríceps','Deltoide anterior'),
    ('Floor press halteres','Peitoral','Tríceps','Deltoide anterior'),
    ('Hex press','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino declinado barra','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino declinado halteres','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino declinado articulado','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino declinado articulado unilateral','Peitoral','Tríceps','Deltoide anterior'),
    ('Flexão tradicional','Peitoral','Tríceps','Deltoide anterior'),
    ('Flexão inclinada','Peitoral','Tríceps','Deltoide anterior'),
    ('Flexão declinada','Peitoral','Tríceps','Deltoide anterior'),
    ('Flexão com elástico','Peitoral','Tríceps','Deltoide anterior'),
    ('Paralelas com foco peitoral','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino unilateral com halter','Peitoral','Tríceps','Core'),
    ('Svend press','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado barra','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado halteres','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado pegada neutra','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado articulado','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado articulado unilateral','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado articulado convergente','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado convergente','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino guilhotina','Peitoral','Deltoide anterior','Tríceps'),
    ('Crucifixo reto halteres','Peitoral','Deltoide anterior',null),
    ('Crucifixo inclinado','Peitoral','Deltoide anterior',null),
    ('Crucifixo declinado','Peitoral','Deltoide anterior',null),
    ('Crucifixo cabo deitado','Peitoral','Deltoide anterior',null),
    ('Peck deck','Peitoral','Deltoide anterior',null),
    ('Peck deck unilateral','Peitoral','Deltoide anterior',null),
    ('Crossover alto','Peitoral','Deltoide anterior',null),
    ('Crossover médio','Peitoral','Deltoide anterior',null),
    ('Crossover baixo','Peitoral','Deltoide anterior',null),
    ('Crucifixo unilateral cabo','Peitoral','Deltoide anterior','Core'),
    ('Puxada frente pronada aberta','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada frente pronada média','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada neutra','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada neutra fechada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada com triângulo','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada supinada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada unilateral','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada unilateral ajoelhada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada unilateral sentada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada articulada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada articulada unilateral','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada articulada convergente','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada Hammer neutra','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada Hammer supinada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada Hammer unilateral','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Barra fixa pronada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Barra fixa neutra','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Barra fixa supinada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Pulldown braços estendidos','Latíssimo do dorso','Redondo maior','Tríceps'),
    ('Pullover polia','Latíssimo do dorso','Redondo maior','Tríceps'),
    ('Pullover máquina','Latíssimo do dorso','Redondo maior','Tríceps'),
    ('Pulldown unilateral','Latíssimo do dorso','Redondo maior','Bíceps'),
    ('Pullover halter','Latíssimo do dorso','Peitoral','Tríceps'),
    ('Remada curvada barra pronada','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada Pendlay','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada Meadows','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada cavalinho','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada cavalinho com apoio de peito','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada baixa pronada','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada peito apoiado','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Seal row','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada Hammer cotovelo médio','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada Hammer cotovelo médio unilateral','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada articulada convergente','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada articulada convergente unilateral','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada articulada com apoio de peito','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada articulada com apoio de peito unilateral','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada articulada pronada','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada curvada barra supinada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada unilateral halter','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada serrote','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada baixa pegada neutra','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada baixa fechada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada baixa supinada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada baixa unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada invertida','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada invertida supinada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer pegada fechada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer fechada unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer pegada neutra','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer neutra unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer supinada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer supinada unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer cotovelo baixo','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada Hammer cotovelo baixo unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada baixa','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada baixa unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada neutra','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada neutra unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada fechada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada fechada unilateral','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada convergente fechada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada supinada','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Gorilla row','Latíssimo do dorso','Bíceps','Core'),
    ('Remada baixa aberta','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada Hammer pegada aberta','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada Hammer aberta unilateral','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada articulada aberta','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada articulada aberta unilateral','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada articulada convergente aberta','Trapézio','Deltoide posterior','Latíssimo do dorso'),
    ('Remada Hammer cotovelo alto','Deltoide posterior','Trapézio','Latíssimo do dorso'),
    ('Remada Hammer cotovelo alto unilateral','Deltoide posterior','Trapézio','Latíssimo do dorso'),
    ('Remada articulada cotovelo alto','Deltoide posterior','Trapézio','Latíssimo do dorso'),
    ('Remada articulada cotovelo alto unilateral','Deltoide posterior','Trapézio','Latíssimo do dorso'),
    ('Remada articulada convergente cotovelo alto','Deltoide posterior','Trapézio','Latíssimo do dorso')
)
insert into public.exercise_library (name, muscle_group, secondary_muscle, secondary_muscle_2, is_global)
select n.name, n.muscle_group, n.secondary_muscle, n.secondary_muscle_2, true
from novos n
where not exists (
  select 1 from public.exercise_library e where lower(e.name) = lower(n.name)
);