-- Seed do banco de exercícios global (EVO CLUB)
with novos(name, muscle_group, secondary_muscle, secondary_muscle_2) as (
  values
    ('Supino reto barra','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino reto halteres','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino inclinado barra','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino inclinado halteres','Peitoral','Deltoide anterior','Tríceps'),
    ('Supino declinado barra','Peitoral','Tríceps','Deltoide anterior'),
    ('Supino máquina','Peitoral','Tríceps','Deltoide anterior'),
    ('Chest press','Peitoral','Tríceps','Deltoide anterior'),
    ('Crucifixo reto halteres','Peitoral','Deltoide anterior',null),
    ('Crucifixo inclinado','Peitoral','Deltoide anterior',null),
    ('Peck deck','Peitoral','Deltoide anterior',null),
    ('Crossover alto','Peitoral','Deltoide anterior',null),
    ('Crossover médio','Peitoral','Deltoide anterior',null),
    ('Crossover baixo','Peitoral','Deltoide anterior',null),
    ('Flexão de braço','Peitoral','Tríceps','Deltoide anterior'),
    ('Paralelas com foco peitoral','Peitoral','Tríceps','Deltoide anterior'),
    ('Puxada frente pronada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada frente neutra','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Puxada supinada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Barra fixa pronada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Barra fixa supinada','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Pulldown unilateral','Latíssimo do dorso','Bíceps','Redondo maior'),
    ('Pullover na polia','Latíssimo do dorso','Redondo maior','Tríceps'),
    ('Remada curvada barra','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada cavalinho','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada baixa','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada máquina','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada unilateral halter','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada serrote','Latíssimo do dorso','Bíceps','Trapézio'),
    ('Remada articulada','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada 45°','Latíssimo do dorso','Trapézio','Bíceps'),
    ('Remada alta aberta','Trapézio','Deltoide posterior','Bíceps'),
    ('Face pull','Deltoide posterior','Trapézio','Manguito rotador'),
    ('Desenvolvimento barra','Deltoide anterior','Deltoide lateral','Tríceps'),
    ('Desenvolvimento halteres','Deltoide anterior','Deltoide lateral','Tríceps'),
    ('Desenvolvimento máquina','Deltoide anterior','Deltoide lateral','Tríceps'),
    ('Arnold press','Deltoide anterior','Deltoide lateral','Tríceps'),
    ('Elevação lateral halteres','Deltoide lateral','Trapézio',null),
    ('Elevação lateral polia','Deltoide lateral','Trapézio',null),
    ('Elevação lateral máquina','Deltoide lateral','Trapézio',null),
    ('Elevação frontal halter','Deltoide anterior','Peitoral',null),
    ('Elevação frontal polia','Deltoide anterior','Peitoral',null),
    ('Crucifixo inverso','Deltoide posterior','Trapézio',null),
    ('Peck deck inverso','Deltoide posterior','Trapézio',null),
    ('Encolhimento barra','Trapézio','Antebraço',null),
    ('Encolhimento halteres','Trapézio','Antebraço',null),
    ('Encolhimento máquina','Trapézio','Antebraço',null),
    ('Remada alta','Trapézio','Deltoide lateral','Bíceps'),
    ('Rosca direta barra','Bíceps','Braquial','Antebraço'),
    ('Rosca direta polia','Bíceps','Braquial','Antebraço'),
    ('Rosca alternada','Bíceps','Braquial','Antebraço'),
    ('Rosca Scott','Bíceps','Braquial','Antebraço'),
    ('Rosca Scott máquina','Bíceps','Braquial','Antebraço'),
    ('Rosca inclinada','Bíceps','Braquial','Antebraço'),
    ('Rosca concentrada','Bíceps','Braquial',null),
    ('Rosca martelo','Braquial','Bíceps','Braquiorradial'),
    ('Rosca martelo corda','Braquial','Bíceps','Braquiorradial'),
    ('Rosca inversa','Braquiorradial','Bíceps','Antebraço'),
    ('Rosca Bayesian','Bíceps','Braquial','Antebraço'),
    ('Tríceps pulley barra','Tríceps',null,null),
    ('Tríceps pulley corda','Tríceps',null,null),
    ('Tríceps francês halter','Tríceps',null,null),
    ('Tríceps francês polia','Tríceps',null,null),
    ('Tríceps testa barra','Tríceps',null,null),
    ('Tríceps testa halteres','Tríceps',null,null),
    ('Tríceps coice','Tríceps',null,null),
    ('Tríceps unilateral polia','Tríceps',null,null),
    ('Supino fechado','Tríceps','Peitoral','Deltoide anterior'),
    ('Paralelas','Tríceps','Peitoral','Deltoide anterior'),
    ('Agachamento livre','Quadríceps','Glúteos','Posterior de coxa'),
    ('Agachamento frontal','Quadríceps','Glúteos','Core'),
    ('Agachamento Smith','Quadríceps','Glúteos','Posterior de coxa'),
    ('Hack squat','Quadríceps','Glúteos','Posterior de coxa'),
    ('Pendulum squat','Quadríceps','Glúteos','Posterior de coxa'),
    ('Leg press 45°','Quadríceps','Glúteos','Posterior de coxa'),
    ('Leg press horizontal','Quadríceps','Glúteos','Posterior de coxa'),
    ('Cadeira extensora','Quadríceps',null,null),
    ('Afundo','Quadríceps','Glúteos','Posterior de coxa'),
    ('Passada','Quadríceps','Glúteos','Posterior de coxa'),
    ('Agachamento búlgaro','Quadríceps','Glúteos','Posterior de coxa'),
    ('Step-up','Quadríceps','Glúteos','Posterior de coxa'),
    ('Sissy squat','Quadríceps',null,null),
    ('Mesa flexora','Posterior de coxa','Gastrocnêmio',null),
    ('Cadeira flexora','Posterior de coxa','Gastrocnêmio',null),
    ('Flexora em pé','Posterior de coxa','Gastrocnêmio',null),
    ('Flexora unilateral','Posterior de coxa','Gastrocnêmio',null),
    ('Stiff barra','Posterior de coxa','Glúteos','Eretor da coluna'),
    ('Stiff halteres','Posterior de coxa','Glúteos','Eretor da coluna'),
    ('Levantamento terra romeno','Posterior de coxa','Glúteos','Eretor da coluna'),
    ('Nordic curl','Posterior de coxa','Gastrocnêmio','Glúteos'),
    ('Good morning','Posterior de coxa','Glúteos','Eretor da coluna'),
    ('Elevação pélvica barra','Glúteos','Posterior de coxa','Quadríceps'),
    ('Elevação pélvica máquina','Glúteos','Posterior de coxa','Quadríceps'),
    ('Glute bridge','Glúteos','Posterior de coxa',null),
    ('Coice na polia','Glúteos','Posterior de coxa',null),
    ('Coice máquina','Glúteos','Posterior de coxa',null),
    ('Abdução máquina','Glúteo médio','Glúteos',null),
    ('Abdução polia','Glúteo médio','Glúteos',null),
    ('Abdução com elástico','Glúteo médio','Glúteos',null),
    ('Agachamento sumô','Glúteos','Quadríceps','Adutores'),
    ('Terra sumô','Glúteos','Posterior de coxa','Adutores'),
    ('Extensão de quadril banco 45°','Glúteos','Posterior de coxa','Eretor da coluna'),
    ('Cadeira adutora','Adutores',null,null),
    ('Adução na polia','Adutores',null,null),
    ('Panturrilha em pé','Gastrocnêmio','Sóleo',null),
    ('Panturrilha máquina em pé','Gastrocnêmio','Sóleo',null),
    ('Panturrilha no leg press','Gastrocnêmio','Sóleo',null),
    ('Panturrilha sentado','Sóleo','Gastrocnêmio',null),
    ('Panturrilha unilateral','Gastrocnêmio','Sóleo',null),
    ('Donkey calf raise','Gastrocnêmio','Sóleo',null),
    ('Abdominal máquina','Reto abdominal','Oblíquos',null),
    ('Crunch solo','Reto abdominal','Oblíquos',null),
    ('Crunch polia','Reto abdominal','Oblíquos',null),
    ('Elevação de pernas','Reto abdominal','Flexores do quadril',null),
    ('Elevação de joelhos','Reto abdominal','Flexores do quadril',null),
    ('Abdominal infra banco','Reto abdominal','Flexores do quadril',null),
    ('Abdominal bicicleta','Reto abdominal','Oblíquos','Flexores do quadril'),
    ('Prancha','Core','Reto abdominal','Oblíquos'),
    ('Prancha lateral','Oblíquos','Core','Glúteo médio'),
    ('Pallof press','Core','Oblíquos',null),
    ('Woodchopper','Oblíquos','Core','Reto abdominal'),
    ('Ab wheel','Reto abdominal','Core','Latíssimo do dorso'),
    ('Extensão lombar','Eretor da coluna','Glúteos','Posterior de coxa'),
    ('Hiperextensão 45°','Eretor da coluna','Glúteos','Posterior de coxa'),
    ('Levantamento terra','Eretor da coluna','Glúteos','Posterior de coxa'),
    ('Flexão de punho','Flexores do antebraço',null,null),
    ('Extensão de punho','Extensores do antebraço',null,null),
    ('Farmer walk','Antebraço','Trapézio','Core')
)
insert into public.exercise_library (name, muscle_group, secondary_muscle, secondary_muscle_2, is_global)
select n.name, n.muscle_group, n.secondary_muscle, n.secondary_muscle_2, true
from novos n
where not exists (
  select 1 from public.exercise_library e
  where lower(e.name) = lower(n.name)
);