import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, Download, FileDown, MessageCircle, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { AssessmentComparisonItem, assessmentDate, COMPARISON_INDICATORS, evolutionTone, fetchClientAssessments, formatAssessmentValue, SEGMENT_KEYS, valueOf } from "@/lib/assessmentComparison";
import { downloadComparisonBlob, generateAndStoreComparisonPdf } from "@/lib/assessmentComparisonPdf";

const GRAPH_KEYS = ["weight", "skeletal_muscle_mass", "fat_mass", "body_fat_pct", "bmi", "visceral_fat"];
const toneClass = { positive: "text-success", negative: "text-destructive", stable: "text-muted-foreground", neutral: "text-primary" } as const;

export default function AvaliacaoCompararResultado() {
  const { id } = useParams<{ id: string }>();
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const clientId = Number(id);
  const idsParam = params.get("ids") || "";
  const ids = useMemo(() => idsParam.split(",").filter(Boolean).slice(0, 5), [idsParam]);
  const [client, setClient] = useState<any>(null);
  const [items, setItems] = useState<AssessmentComparisonItem[]>([]);
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetchClientAssessments(clientId).then(r => { setClient(r.client); setItems(r.items.filter(i => ids.includes(i.id)).sort((a, b) => +new Date(assessmentDate(a)) - +new Date(assessmentDate(b)))); }).catch(e => toast.error(e.message)); }, [clientId, ids]);
  const first = items[0], latest = items[items.length - 1];
  const changes = useMemo(() => COMPARISON_INDICATORS.flatMap(ind => { if (!first || !latest) return []; const a = valueOf(first, ind.key, "fallback" in ind ? ind.fallback : undefined); const b = valueOf(latest, ind.key, "fallback" in ind ? ind.fallback : undefined); if (a == null || b == null) return []; const delta = b - a; return [{ ...ind, delta, pct: a === 0 ? null : delta / a * 100, toneValue: evolutionTone(ind.tone, delta, b, a) }]; }), [first, latest]);
  const positives = changes.filter(c => c.toneValue === "positive");
  const attentions = changes.filter(c => c.toneValue === "negative");
  const generate = async (action: "view" | "download" | "share") => { setBusy(true); try { const r = await generateAndStoreComparisonPdf(clientId, items.map(i => i.id)); if (action === "download") downloadComparisonBlob(r.blob, r.name); else if (action === "view") { const url = URL.createObjectURL(r.blob); window.open(url, "_blank"); setTimeout(() => URL.revokeObjectURL(url), 60000); } else { const file = new File([r.blob], r.name, { type: "application/pdf" }); if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) await navigator.share({ title: "Comparativo EVO Club", files: [file] }); else { downloadComparisonBlob(r.blob, r.name); window.open(`https://wa.me/?text=${encodeURIComponent("Olá! O comparativo EVO Club foi baixado neste dispositivo para anexar à conversa.")}`, "_blank"); } } toast.success("Comparativo salvo no histórico do aluno."); } catch (e: any) { toast.error(e?.message || "Não foi possível gerar o PDF."); } finally { setBusy(false); } };
  if (items.length < 2) return <div className="p-6"><p className="font-dm text-sm text-muted-foreground">Selecione ao menos duas avaliações válidas.</p><Button className="mt-4" onClick={() => navigate(`/admin/clientes/${clientId}/avaliacoes/comparar`)}>Voltar à seleção</Button></div>;
  const consecutive = items.slice(1).map((item, index) => ({ previous: items[index], current: item }));
  return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
      <div className="flex gap-3"><Button variant="ghost" size="icon" aria-label="Voltar" onClick={() => navigate(`/admin/clientes/${clientId}/avaliacoes/comparar`)}><ArrowLeft size={20} /></Button><div><h1 className="font-barlow text-2xl font-bold uppercase">Comparativo de avaliações</h1><p className="font-dm text-sm text-muted-foreground">{client?.name} • {items.length} avaliações</p></div></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => window.print()}><Printer size={14} className="mr-1.5" />Imprimir</Button><Button variant="outline" size="sm" onClick={() => generate("share")} disabled={busy}><MessageCircle size={14} className="mr-1.5" />WhatsApp</Button><Button variant="outline" size="sm" onClick={() => generate("view")} disabled={busy}><FileDown size={14} className="mr-1.5" />Visualizar PDF</Button><Button size="sm" onClick={() => generate("download")} disabled={busy}><Download size={14} className="mr-1.5" />Baixar PDF</Button></div>
    </div>

    <section><h2 className="mb-3 font-barlow text-lg font-bold uppercase">Linha do tempo</h2><div className="overflow-x-auto"><div className="flex min-w-max items-center gap-0 py-3">{items.map((item, index) => <div key={item.id} className="flex items-center"><div className="w-40 text-center"><div className="mx-auto mb-2 h-3 w-3 rounded-full bg-primary ring-4 ring-primary/10"/><p className="font-barlow font-bold">{new Date(assessmentDate(item)).toLocaleDateString("pt-BR")}</p><p className="font-dm text-xs text-muted-foreground">Avaliação {index + 1}</p></div>{index < items.length - 1 && <div className="h-px w-12 bg-primary/30"/>}</div>)}</div></div></section>

    <section><h2 className="mb-3 font-barlow text-lg font-bold uppercase">Tabela comparativa</h2><div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[760px] font-dm text-xs"><thead className="bg-muted/70"><tr><th className="p-3 text-left">Indicador</th>{items.map(i => <th key={i.id} className="p-3 text-right">{new Date(assessmentDate(i)).toLocaleDateString("pt-BR")}</th>)}<th className="p-3 text-right">Evolução total</th></tr></thead><tbody>{[...COMPARISON_INDICATORS, ...SEGMENT_KEYS.map(([key, label]) => ({ key, label, unit: "kg", tone: "neutral" as const }))].map(ind => { const vals = items.map(item => valueOf(item, ind.key, "fallback" in ind ? ind.fallback : undefined)); const a = vals[0], b = vals[vals.length - 1], delta = a == null || b == null ? null : b - a; const pct = delta == null || a === 0 ? null : delta / a * 100; const tone = delta == null ? "neutral" : evolutionTone(ind.tone, delta, b, a); return <tr key={ind.key} className="border-t border-border"><td className="p-3 font-medium">{ind.label}</td>{vals.map((v, index) => <td key={items[index].id} className="p-3 text-right">{formatAssessmentValue(v, ind.unit)}</td>)}<td className={`p-3 text-right font-bold ${toneClass[tone]}`}>{delta == null ? "Não informado" : <>{delta > 0 ? "+" : ""}{delta.toLocaleString("pt-BR", { maximumFractionDigits: 2 })} {"deltaUnit" in ind ? ind.deltaUnit : ind.unit}{pct != null && <span className="block text-[10px] font-normal">{pct > 0 ? "+" : ""}{pct.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%</span>}</>}</td></tr>; })}</tbody></table></div></section>

    <section><h2 className="mb-3 font-barlow text-lg font-bold uppercase">Variações entre avaliações</h2><div className="grid gap-3 md:grid-cols-2">{consecutive.map(pair => <div key={pair.current.id} className="rounded-lg border border-border bg-card p-4"><p className="font-dm text-xs font-medium text-muted-foreground">{new Date(assessmentDate(pair.previous)).toLocaleDateString("pt-BR")} → {new Date(assessmentDate(pair.current)).toLocaleDateString("pt-BR")}</p><div className="mt-3 space-y-2">{COMPARISON_INDICATORS.slice(0, 6).map(ind => { const a = valueOf(pair.previous, ind.key, "fallback" in ind ? ind.fallback : undefined); const b = valueOf(pair.current, ind.key, "fallback" in ind ? ind.fallback : undefined); const delta = a == null || b == null ? null : b - a; const pct = delta == null || a === 0 ? null : delta / a * 100; return <div key={ind.key} className="flex justify-between gap-3 font-dm text-xs"><span>{ind.label}</span><strong>{delta == null ? "Não informado" : `${delta > 0 ? "+" : ""}${delta.toLocaleString("pt-BR", { maximumFractionDigits: 2 })}${pct == null ? "" : ` (${pct > 0 ? "+" : ""}${pct.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%)`}`}</strong></div>; })}</div></div>)}</div></section>

    <section><h2 className="mb-3 font-barlow text-lg font-bold uppercase">Gráficos de evolução</h2><div className="grid gap-4 md:grid-cols-2">{GRAPH_KEYS.map(key => { const ind = COMPARISON_INDICATORS.find(i => i.key === key); if (!ind) return null; const data = items.map(item => ({ date: new Date(assessmentDate(item)).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "2-digit" }), value: valueOf(item, ind.key, "fallback" in ind ? ind.fallback : undefined) })); return <div key={key} className="rounded-lg border border-border bg-card p-4"><h3 className="mb-3 font-dm text-sm font-medium">{ind.label} ({ind.unit || "nível"})</h3><div className="h-52"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: -12, right: 12 }}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }} domain={["auto", "auto"]}/><Tooltip formatter={(v: any) => [v == null ? "Não informado" : Number(v).toLocaleString("pt-BR"), ind.label]}/><Line type="monotone" dataKey="value" stroke="hsl(var(--primary))" strokeWidth={2.5} connectNulls={false}/></LineChart></ResponsiveContainer></div></div>; })}</div></section>

    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><h2 className="font-barlow text-lg font-bold uppercase">Resumo profissional</h2><p className="mt-2 font-dm text-sm text-muted-foreground">Entre a primeira e a última avaliação, {positives.length} indicador(es) apresentou(aram) evolução positiva e {attentions.length} exige(m) atenção. A mudança de peso permanece neutra quando analisada isoladamente.</p></div><div className="rounded-lg border border-success/30 bg-success/5 p-4"><h2 className="font-barlow text-lg font-bold uppercase text-success">Pontos positivos</h2><ul className="mt-2 space-y-1 font-dm text-sm">{positives.length ? positives.map(p => <li key={p.key}>• {p.label}: {p.delta > 0 ? "+" : ""}{p.delta.toLocaleString("pt-BR", { maximumFractionDigits: 2 })} {p.unit}</li>) : <li>Nenhum ponto classificável nos dados disponíveis.</li>}</ul></div><div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4"><h2 className="font-barlow text-lg font-bold uppercase text-destructive">Pontos de atenção</h2><ul className="mt-2 space-y-1 font-dm text-sm">{attentions.length ? attentions.map(p => <li key={p.key}>• {p.label}: {p.delta > 0 ? "+" : ""}{p.delta.toLocaleString("pt-BR", { maximumFractionDigits: 2 })} {p.unit}</li>) : <li>Nenhum ponto de atenção classificável.</li>}</ul></div></section>
  </div>;
}